### DISCUSSION TITLE
根据 yml 文件自动生成函数

### DISCUSSION THREAD

**Discussion by Drelf2018** [Nemo2011/bilibili-api#307] [Ideas]
其实 #288 [这个](https://github.com/Nemo2011/bilibili-api/pull/288#issuecomment-1565313499) 我前段时间研究了下，但是不知道有啥用

```python
from typing import Callable, Dict, List, Optional, Tuple, TypeVar

from yaml import FullLoader, load

from bilibili_api.utils.network_httpx import request

T = TypeVar("T")


def dfs(
    root: Optional[T] = None,
    getchildren: Callable[[T], List[T]] = None,
):
    """
    ### 深度优先搜索
    
    root: 起点 不为空时自动启动一次
    
    getchildren: 获取子节点函数
    """

    def warpper(preorder: Callable):
        def run(root: T):
            dict_path = []
            nodes: List[Optional[Tuple[str, T]]] = [("root", root)]
            while nodes:
                node = nodes.pop(0)
                if node is None:
                    dict_path.pop(-1)
                else:
                    path, info = node
                    dict_path.append(path)
                    juction = "API" + '"]["'.join(dict_path)[6:] + '"]'
                    if preorder(juction, info) is True:
                        nodes = [*getchildren(info), None, *nodes]
                    else:
                        dict_path.pop(-1)
        if root is not None:
            run(root)
        return run
    return warpper


with open("user.yml", "r", encoding="utf-8") as fp:
    API: dict = load(fp, FullLoader)


function_format = '''

async def {function}({variable_params}) -> {result}:
    """
    {comment}
    """

    api = {api}
    params = {constant_params}
    return await request("{method}", api["url"], params=params)
'''


def write_function(s: str, path: str = __file__):
    with open(path, "a", encoding="utf-8") as fp:
        fp.write(s)


@dfs(API, lambda node: node.items())
def makeFunction(path: str, node: dict):
    name = node.get("function")
    if name is None:
        return True
    params: Dict[str, dict] = node["params"]

    variable = []
    constant = []

    for param, info in params.items():
        if info.get("variable", False):
            hint = param
            if info.get("type") is not None:
                hint += f": {info['type']}"
            if info.get("value") is not None:
                v = info["value"]
                if isinstance(v, str):
                    v = '"' + v + '"'
                hint += f" = {v}"
            variable.append(hint)
            constant.append(f'"{param}": {param}')
        else:
            v = info["value"]
            if isinstance(v, str):
                v = '"' + v + '"'
            constant.append(f'"{param}": {v}')

    node["variable_params"] = ", ".join(variable)
    node["constant_params"] = "{\n\t\t" + ",\n\t\t".join(constant) + "\n\t}"

    node["api"] = path
    write_function(function_format.format_map(node))
```

同目录下有 `user.yml` 文件

```yaml
info:
  info:
    function: get_user_info
    url: "https://api.bilibili.com/x/space/wbi/acc/info"
    method: "GET"
    verify: false
    params:
      self:
        variable: true
      mid: 
        type: int
        describe: uid
        variable: true
      token: 
        type: str
        value: ""
        describe: 密钥
      platform:
        type: str
        value: "web"
        describe: 平台
      web_location:
        type: int
        value: 1550101
    result: dict
    comment: "用户基本信息"
```

最后结果

```python
async def get_user_info(self, mid: int) -> dict:
    """
    用户基本信息
    """

    api = API["info"]["info"]
    params = {
		"self": self,
		"mid": mid,
		"token": "",
		"platform": "web",
		"web_location": 1550101
	}
    return await request("GET", api["url"], params=params)
```
